import { PageContent, PageTitle } from 'components/styled/App.styled'

const Terms = () => {
  return (
    <>
      <PageTitle>terms</PageTitle>
      <PageContent>
        This site is operated by The Pixel Portraits (“TPP”). By using this site
        and/or purchasing a portrait created by TPP, you confirm that you accept
        these terms of use and you agree to comply with them.
        <br />
        <br />
        The portraits created by TPP are digital collectibles (NFTs) transferred
        via OpenSea. This website is only an interface allowing users to reserve
        their place in the queue to request a portrait and pay a deposit. Users
        are entirely responsible for the safety and management of their own
        private ethereum wallets and validating all transactions and contracts
        generated by this website before approval. Furthermore, as the TPP smart
        contract runs on the ethereum network, there is no ability to undo,
        reverse or restore any transactions. The portraits created by TPP are
        artistic interpretations intended as parodies, all portraits provided
        are accepted by each user as final and there will be no obligation
        whatsoever for TPP to make any further changes after completion
        <br />
        <br />
        This website and its connected services are provided “as is” and “as
        available” without any representation or warranty (whether express or
        implied) of any kind. By using this website you are accepting sole
        responsibility for any and all transactions involving TPP digital
        collectibles. TPP reserves absolute discretion to reject any requests
        made for any reason.
        <br />
        <br />
        TPP is the owner or the licensee of all intellectual property rights on
        this site and in the material published on it. Those works are protected
        by copyright laws and treaties around the world. All such rights are
        reserved.
        <br />
        <br />
        TPP does not guarantee that this site will be secure or free from bugs.
        You are responsible for configuring your information technology,
        computer programmes and platform to access our site. You should use your
        own virus protection software. You must not misuse our site by knowingly
        introducing viruses, bugs, worms, logic bombs or other material that is
        malicious or technologically harmful.
        <br />
        <br />
        TPP may update and/or change this site and these terms from time to
        time.
      </PageContent>
    </>
  )
}

export default Terms
